export const TEXTS = {
    navigation: {
        home: "Descubrir",
        activity: "Tienda",
        editorial: "Comunidad",
        profile: "Ver Perfil",
        logout: "Cerrar Sesión",
        sync: "Conectar",
        admin: "Administrar",
        brand: "Oldie but Goldie"
    },
    home: {
        searchPlaceholder: "Artista, Álbum o Referencia...",
        systemVersion: "OLDIE BUT GOLDIE",
        searchTitle: "Descubrí tu próximo álbum musical",
        resultsTitle: "RESULTADOS",
        loadingDiscogs: "Buscando en la web...",
        analyzingDB: "Analizando base de datos...",
        noResults: "No se encontraron resultados para",
        clearSearch: "Limpiar búsqueda",
        loadMore: "Cargar Más",
        filters: {
            all: "todo",
            artists: "artistas",
            albums: "álbumes"
        }
    },
    item: {
        detailTitle: "Detalle de Obra",
        share: "Compartir",
        year: "Año",
        genre: "Género",
        changeSelection: "Cambiar Selección",
        changeTitle: "Cambiar de Título",
        consultSimilar: "Cargar otra orden",
        format: "Formato",
        condition: "Condición",
        operation: "¿Qué querés hacer?",
        buyIntent: "COMPRAR",
        sellIntent: "VENDER",
        receiptTitle: "Recibo de Actividad",
        registrationDate: "Fecha Registro",
        userPrice: "Precio Usuario",
        toConfirm: "A Confirmar",
        unknown: "Desconocido",
        contactOrder: "Contactar por este pedido",
        steps: {
            format: "[ 01 ] Seleccionar Formato",
            condition: "[ 02 ] Estado",
            addAnother: "+ Añadir otro ítem al lote",
            finishOrder: "FINALIZAR MI ORDEN"
        },
        recommendations: "Otros álbumes que podrían interesarte"
    },
    negotiation: {
        sellPriceTitle: "Precio de Venta",
        marketValueSubtitle: "Establecer valor de mercado para tu ítem",
        consultingMarket: "Consultando valor de mercado global...",
        marketRef: "Valor de referencia global (Discogs): US$",
        currencyLabel: "[ 03 ] Moneda",
        priceLabel: "[ 04 ] Precio",
        currencyARS: "Pesos Argentinos",
        currencyUSD: "Dólares USD",
        addSellBatch: "Añadir ítem al lote (+)",
        back: "Atrás"
    },
    auth: {
        syncNetwork: "Conectar a la Red",
        securityProtocol: "Protocolo de seguridad para persistir intención",
        googleSignIn: "Continuar con Google",
        manualCredentials: "O Credenciales Manuales",
        emailPlaceholder: "Email de Terminal...",
        passwordPlaceholder: "Clave Técnica...",
        connecting: "CONECTANDO...",
        registerAndLink: "REGISTRARSE",
        levelElite: "Nivel Elite",
        masterArchitect: "Arquitecto Maestro",
        proCollector: "Coleccionista"
    },
    success: {
        orderRegistered: "Orden Registrada",
        successMessage: "Tu orden ha sido registrada. Contacta a Oldie but Goldie para obtener más detalles de tu pedido.",
        contactWhatsApp: "Contactar por WhatsApp",
        newSearch: "Nueva Búsqueda"
    },
    activity: {
        availableNow: "★ Disponible",
        buyFull: "¡COMPRAR!",
        requiredAction: "Acción Requerida"
    },
    badges: {
        forSale: "EN VENTA",
        buying: "EN COMPRA",
        storeObg: "★ Tienda OBG",
        user_label: "👤 USUARIO"
    },
    showcase: {
        title: "Boutique de Vinilos",
        subtitle: "Joyas de la Corona",
        viewMore: "Ver más",
        officialStore: "Colección Oficial"
    },
    details: {
        technicalSheet: "Ficha Técnica",
        label: "Sello",
        year: "Año",
        country: "País",
        genre: "Género",
        showLess: "Mostrar menos",
        showAll: "Ver todos los discos"
    },
    gatekeeper: {
        loginToNegotiate: "Inicia sesión para negociar o proponer precio"
    },
    bulk: {
        title: "Ingesta Masiva",
        subtitle: "Acelerador de Inventario. Identificación y pre-validación automática con Discogs.",
        dropTitle: "Arrastra tu matriz aquí",
        dropSubtitle: "Soporta CSV y XLSX (Excel)",
        columnRequirements: "Requisito de Columnas",
        columnRequirementsDesc: "Para que el motor Stitch reconozca el catálogo automáticamente, tu archivo debe contener headers con palabras clave.",
        processingBatch: "Procesando Lote",
        rateLimiting: "Aplicando rate limiting (Chunks de 5)",
        itemsTotal: "Ítems Total",
        ready: "Listos",
        doubt: "Duda",
        fail: "Fallo",
        strategyTitle: "Estrategia de Salida",
        individualMode: "Modo Individual",
        individualModeDesc: "Crear una orden de venta independiente para cada disco seleccionado en la base de datos.",
        bundleMode: "Modo Lote Especial",
        bundleModeDesc: "Generar una única orden agrupando todos los discos. ¡Ideal para lotes DJ!",
        priceAdjustment: "Ajuste de Precio Total",
        publishBundle: "Publicar Lote",
        clearWorkspaceConfirm: "¿Estás seguro de limpiar la mesa de trabajo? Esto descartará el escaneo actual.",
        unsupportedFormat: "Formato no soportado. Usa .CSV o .XLSX",
        sanitizingDB: "Sanitizando base de datos global...",
        operationFinished: "Operación Finalizada. Revisa la consola.",
        baseCentral: "Base Central",
        workspace: "Mesa de Trabajo",
        registeredOfficially: "Registrados Oficialmente",
        noIdentity: "Sin Identidad Discogs",
        falseAlarm: "Falsa Alarma"
    },
    profile: {
        syncing: "Sincronizando Perfil de Coleccionista...",
        acceptingProposal: "Aceptando propuesta...",
        proposalAccepted: "¡Propuesta aceptada! La venta se ha finalizado.",
        definePrice: "Definir Precio de Venta",
        pricePlaceholder: "Monto",
        updatingStatus: "Actualizando estado...",
        counterOfferReceived: "Nueva Contraoferta",
        ourOffer: "Nuestra Oferta",
        acceptError: "Hubo un error al aceptar la propuesta.",
        confirmAcceptProposal: "¿Estás seguro de que deseas aceptar esta propuesta? Esta acción finalizará el trato.",
        processing: "Procesando...",
        confirmingDeal: "Confirmando trato...",
        saleFinished: "Venta Finalizada 🎉",
        saleSuccess: "¡Felicidades! Has finalizado la venta. Coordina el pago por WhatsApp.",
        genericError: "Hubo un error al procesar la solicitud.",
        sendingCounterOffer: "Enviando contraoferta...",
        userCounterOffer: "Nueva Contraoferta del Usuario",
        counterOfferSent: "Has enviado una contraoferta. Espera la respuesta de Oldie but Goldie.",
        receiptTitle: "OLDIE BUT GOLDIE - COMPROBANTE DE ORDEN",
        orderId: "ORDEN ID",
        date: "FECHA",
        client: "CLIENTE",
        items: "ITEMS",
        finalPrice: "PRECIO FINAL",
        receiptStatus: "ESTADO: VENTA FINALIZADA",
        thanks: "Gracias por confiar en Oldie but Goldie.",
        tabs: {
            overview: "General",
            orders: "Ordenes",
            wantlist: "Deseados"
        },
        stats: {
            orders: "Ordenes",
            wantlist: "Deseados",
            level: "Nivel"
        },
        recentOrders: "Ordenes Recientes",
        noOrders: "No tienes ordenes aún.",
        searchFirst: "Buscar tu primer vinilo/cd/cassette",
        myOrders: "Mis Ordenes",
        historyDesc: "Historial de ordenes de compra y venta registradas.",
        noOrdersSector: "No se detectaron ordenes en este sector.",
        startSearch: "Iniciar Búsqueda de Disco",
        wantlistTitle: "Lista de Deseados",
        highValueDesc: "Siguiendo adquisiciones de alto valor.",
        noWantlistSector: "No se detectaron entradas en este sector.",
        startDiscovery: "Iniciar Descubrimiento de Datos",
        orderDetail: "Detalle de Orden"
    },
    admin: {
        syncingOrders: "Sincronizando Base de Ordenes...",
        updatingStatus: "Actualizando estado...",
        orderUpdate: "Actualización de Orden",
        settingPrice: "Definiendo precio...",
        counterOfferReceived: "Contraoferta Recibida",
        sendingQuote: "Enviando cotización...",
        offerReceived: "Oferta Recibida",
        ourOffer: "Nuestra Oferta",
        managementTitle: "Gestión de Ordenes",
        managementDesc: "Panel de control administrativo. Click en una orden para ver detalles y operar.",
        purgeData: "Purga de Datos",
        syncing: "Sincronizando...",
        stats: {
            pending: "Pendientes",
            quoted: "Cotizados",
            negotiating: "Negociando",
            finished: "Finalizados",
            completed: "Completados",
            total: "Total"
        },
        filter: "Filtrar:",
        filterAll: "Todos",
        dealClosed: "Trato Cerrado",
        negotiationFinished: "La negociación ha concluido con éxito.",
        timeline: "Línea de Tiempo de Negociación",
        obgLabel: "OBG (Tú)",
        clientLabel: "Cliente",
        definePrice: "Definir Precio de Venta/Lote",
        pricePlaceholder: "Precio contraoferta...",
        priceSaved: "Precio Guardado ✓",
        statusOptions: {
            pending: "Pendiente",
            quoted: "Cotizado",
            negotiating: "En Negociación",
            counteroffered: "Precio Definido",
            pending_acceptance: "Esperando Cliente",
            offer_sent: "Oferta Enviada",
            venta_finalizada: "Venta Finalizada",
            completed: "Completado",
            cancelled: "Cancelado"
        },
        confirmSetPrice: (price: number, currency: string) => `¿Confirmas definir un precio de ${currency === "USD" ? "US$" : "$"} ${price.toLocaleString()} para este pedido?`,
        dashboard: {
            title: "Métricas de Tráfico",
            subtitle: "Rendimiento SEO y Search Console en tiempo real",
            dominantKeywords: "Análisis de Demanda (Top 100)",
            searchPlaceholder: "Filtrar palabras clave...",
            metrics: {
                clicks: "Clics Totales",
                impressions: "Impresiones",
                ctr: "CTR Promedio",
                position: "Posición Media"
            }
        },
        editorial: {
            title: "Consola Editorial",
            description: "Gestiona contenido, entrevistas y despachos sónicos.",
            newDispatch: "Nuevo Despacho",
            intelDispatches: "Despachos Intel",
            protocolSubscribers: "Suscriptores de Protocolo",
            noDispatches: "No hay despachos en la base de datos.",
            noSubscribers: "No hay suscripciones activas detectadas.",
            deleteDispatchConfirm: "¿Estás seguro de que deseas eliminar este despacho?",
            terminateSubConfirm: "¿Terminar suscripción?",
            modifyDispatch: "Modificar Despacho",
            initialiseDispatch: "Inicializar Despacho",
            dispatchTitle: "Título del Despacho",
            intelCategory: "Categoría Intel",
            briefExcerpt: "Breve Extracto",
            authorName: "Nombre del Autor",
            imageSource: "Fuente de Imagen (URL)",
            readDuration: "Duración de Lectura",
            protocolStatus: "Estado del Protocolo",
            commitDispatch: "Confirmar Despacho",
            escAbort: "Esc Abort"
        }
    },
    common: {
        recent: "Reciente",
        back: "Atrás",
        save: "Guardar",
        private: "Privado",
        close: "Cerrar",
        cancel: "Cancelar",
        confirm: "Confirmar",
        delete: "Eliminar",
        loadingGeneric: "Cargando...",
        notifications: "Notificaciones",
        noNotifications: "No hay notificaciones",
        readAll: "Leer todas",
        now: "Ahora",
        syncingIdentity: "Sincronizando Identidad...",
        locatingBatch: "Localizando Lote...",
        loadingData: "Cargando datos...",
        batchNotFound: "Lote No Encontrado",
        batchAccessDenied: "El acceso a este lote no está disponible o la referencia ha expirado.",
        backToCatalog: "Volver al Catálogo",
        batchDetail: "Detalle del Lote",
        batchDescription: "Lote de vinilos en Oldie but Goldie",
        pieceDescription: "Pieza de colección.",
        itemsInvolved: "Ítems Involucrados",
        noDiscsInBatch: "No hay discos en este lote",
        negotiationSummary: "Resumen de Negociación",
        initialUserOffer: "Oferta Inicial del Usuario",
        latestUserOffer: "Última Propuesta del Usuario",
        obgOffer: "Propuesta de Oldie but Goldie",
        latestObgOffer: "Última Propuesta de OBG",
        initiatedBy: "Iniciado por",
        registeredCollector: "Coleccionista Registrado",
        orderStatus: "Estado de la Orden",
        waitingAcceptance: "Esperando Aceptación",
        loading: {
            safetyInstruction: "Por favor no cierres la aplicación, estamos procesando los datos de forma segura."
        },
        seo: {
            defaultTitle: "Oldie but Goldie - Archivos de Audio y Vinilos",
            defaultDescription: "El sistema definitivo para el coleccionismo físico. Explora nuestro archivo, cotiza en tiempo real, compra o vende reliquias con nosotros.",
            home: {
                title: "Oldie but Goldie | Compra y Venta de Vinilos en Argentina",
                desc: "Encontrá tus próximos vinilos, CDs y cassettes. Sistema de cotización en tiempo real y archivo cultural sonoro.",
                keys: "vinilos, discos, coleccionismo, música analógica, compra venta vinilos argentina",
                ogImage: "https://firebasestorage.googleapis.com/v0/b/vinilos-app-e1d2c.appspot.com/o/brand%2Flogo_og.png?alt=media"
            },
            activity: {
                title: "Actividad en Tiempo Real | Comprá o vendé Vinilos",
                desc: "Monitoreo en vivo de transacciones de discos de colección. Transparencia y fluidez en el mercado sónico.",
                keys: "actividad vinilos, mercado discos, transacciones música, coleccionismo vivo",
                ogImage: "https://firebasestorage.googleapis.com/v0/b/vinilos-app-e1d2c.appspot.com/o/brand%2Factivity_og.png?alt=media"
            },
            editorial: {
                title: "Comunidad y Editorial | Oldie but Goldie",
                desc: "Despachos de inteligencia musical, entrevistas y cultura del vinilo.",
                keys: "editorial música, cultura vinilo, entrevistas artistas, noticias coleccionismo",
                ogImage: "https://firebasestorage.googleapis.com/v0/b/vinilos-app-e1d2c.appspot.com/o/brand%2Feditorial_og.png?alt=media"
            }
        },
        negotiation: {
            obgOffer: "Oferta de OBG",
            proposalReceived: "Propuesta Recibida",
            definedPrice: "Oldie but Goldie ha definido un precio para tu lote.",
            finalPrice: "Precio Final",
            acceptOffer: "Aceptar Oferta",
            rejectOffer: "Rechazar"
        },
        adminDashboard: {
            title: "OBG Dashboard",
            description: "Admin Dashboard",
            liveInteractions: "Live Interactions",
            uniqueSpectators: "Unique Spectators",
            argentinaLeads: "Argentina Leads",
            targetRegions: "Target Regions",
            geographicHotspots: "Geographic Hotspots",
            hits: "Hits",
            harvesterActive: "Harvester Active",
            harvesterDescription: "The Argentina Harvester tool is currently scanning Discogs for new collectors. New leads will appear in your database automatically.",
            viewLeadDatabase: "View Lead Database"
        },
        batchReview: {
            batchRegistered: "Lote Registrado",
            intentionsRegistered: "Tus orden fue registrada. Contacta a Oldie but Goldie para procesar tu pedido.",
            contactWhatsApp: "Contactar por WhatsApp",
            backToStart: "Volver al Inicio",
            batchEmpty: "Tu Lote está vacío",
            exploreCatalog: "Explorar Catálogo",
            reviewBatch: "Revisar Lote",
            selectedDiscs: "Ítems Seleccionados",
            processOrder: "Procesar Pedido",
            batchIntent: "¿Queres comprar o vender?",
            iWantToBuy: "Quiero Comprar",
            iWantToSell: "Quiero Vender",
            intendedPrice: "Precio pretendido por el lote",
            confirmAndSend: "CONFIRMAR Y ENVIAR",
            linkGoogle: "Vincular con Google",
            manualAuth: "O Manual",
            registerAndSend: "REGISTRARSE Y ENVIAR",
            processingOrder: "Procesando tu Pedido...",
            syncingGoogle: "Sincronizando con Google...",
            authenticatingUser: "Autenticando usuario...",
            confirmIntent: "Debes seleccionar la intención del lote para continuar.",
            validPriceRequired: "Debes ingresar un precio pretendido válido para continuar.",
            submissionError: "Error al procesar el lote.",
            authError: "Error en autenticación. Verifique sus credenciales.",
            googleLinkError: "Error al vincular con Google.",
            systemError: "Error del Sistema: No se pudo determinar el tipo de transacción.",
            processDescription: "Se enviará el lote al administrador para iniciar las gestiones unificadas.",
            connecting: "CONECTANDO..."
        },
        publicActivity: {
            verifiedFeed: "Feed Público de Oldie But Goldie",
            recentActivity: "Actividad Reciente",
            exploreDiscs: "Explora los discos/cds/cassettes que están en negociación.",
            noActivity: "Sin Actividad",
            noPublicOrders: "No hay órdenes públicas registradas aún.",
            activityTitle: "Actividad Reciente | Oldie but Goldie",
            activityDesc: "Últimas compras, cotizaciones y ventas en tiempo real.",
            activityName: "Feed de Actividad de Vinilos",
            activityFeedDesc: "Monitoreo en tiempo real del catálogo rotativo de Oldie but Goldie"
        },
        auth: {
            login: "Iniciar Sesión",
            register: "Registrarse",
            welcomeBack: "Bienvenido de Nuevo",
            createAccount: "Crear Cuenta",
            accessArchive: "Comprá o vende tus vinilos con Oldie But Goldie",
            joinCommunity: "Únete a la comunidad global de coleccionistas de vinilos/cds/cassettes.",
            emailPlaceholder: "tu@email.com",
            passwordPlaceholder: "••••••••",
            syncArchive: "Sincronizando Archivo...",
            initProtocol: "Inicializando Protocolo...",
            syncGoogle: "Sincronizando vía Google...",
            invalidCredentials: "Credenciales inválidas. Por favor, verifica tu email y contraseña.",
            weakPassword: "La contraseña es muy débil. Usa al menos 6 caracteres.",
            unauthorizedDomain: "Este dominio no está autorizado para la autenticación.",
            authFailed: "La autenticación falló. Por favor, intenta de nuevo.",
            googleSignInFailed: "El inicio de sesión con Google falló.",
            passwordTooShort: "La contraseña debe tener al menos 6 caracteres.",
            noAccount: "¿No tienes un identificador de archivo?",
            hasAccount: "¿Ya participas en el colectivo?",
            createIndex: "Crear Índice",
            loginSignal: "Señal de Inicio",
            google: "Google",
            github: "Github",
            protocol: "Protocolo",
            synchronize: "Sincronizar",
            initialize: "Inicializar"
        },
        events: {
            welcome: "Conexión establecida. Radar musical de Argentina activo. ¿Qué banda, género o fecha buscas en el circuito?",
            connectionError: "Error de conexión. Sistema inoperativo [API Key Required].",
            interference: "El radar está experimentando interferencias. Reintentando conexión...",
            reset: "Radar reiniciado. Coordenadas musicales limpias.",
            purgeConfirm: "¿Seguro que deseas purgar el historial del radar?",
            title: "Eventos AI",
            subtitle: "Radar de Escena Argentina",
            clearChat: "Limpiar Conversación",
            inputPlaceholder: "Consultar ciclo, fecha o banda..."
        },
        syncingEditorial: "Sincronizando Grilla Editorial...",
        transmissionProtocolEstablished: "Protocolo de transmisión establecido. Bienvenido al Protocolo Sónico.",
        connectionError: "Error de conexión. Reinicializando.",
        culturalArchiveEmpty: "El archivo cultural está actualmente vacío.",
        nextSyncCycle: "Vuelve durante el próximo ciclo de sincronización.",
        featured: "Destacado",
        novelty: "Novedad",
        analyst: "Analista",
        readArticle: "Leer Artículo",
        intelDispatches: "Intel Despachos",
        monthlyMetadata: "Metadatos mensuales de nuestra red global.",
        all: "Todos",
        interviews: "Entrevistas",
        culture: "Cultura",
        equipment: "Equipos",
        seeNote: "Ver Nota",
        newsDesk: "Mesa de Noticias",
        joinProtocol: "Súmate al Protocolo",
        highFidelityDespatches: "Recibe despachos de alta fidelidad e inteligencia de estudio directo a tu terminal.",
        terminalID: "ID de Terminal (Email)",
        linking: "Vinculando...",
        initialize: "Inicializar",
        encryptedVia: "Encriptado vía Protocolo SonicVault 3.0",
        loadingArticle: "Cargando Artículo...",
        articleNotFound: "Artículo no encontrado",
        backToEditorial: "Volver a Editorial",
        author: "Autor",
        readingTime: "Lectura",
        share: "Compartir",
        endOfDispatch: "Fin del despacho",
        stayTuned: "Gracias por leer. Mantente sintonizado para más inteligencia sónica.",
        exploreOtherArticles: "Explorar Otros Artículos",
        sonicConnectionLost: "Sonic connection lost.",
        backToDiscovery: "Back to Discovery",
        syncToCollect: "Por favor, sincroniza para coleccionar.",
        syncToWantlist: "Por favor, sincroniza para tu lista de deseos.",
        archivingCollection: "Archivando en Colección...",
        removingCollection: "Removiendo de Colección...",
        searchingFavorites: "Buscando en Favoritos...",
        removingFavorites: "Removiendo de Favoritos...",
        archived: "Archivado",
        collect: "Coleccionar",
        target: "Objetivo",
        favorites: "Favoritos",
        transmissionLink: "Enlace de Transmisión",
        marketLogic: "Lógica de Mercado",
        basePrice: "Precio Base",
        resonance: "Resonancia",
        communityVotes: "Votos de la Comunidad",
        analyzeOnDiscogs: "Analizar en Discogs",
        lp: "LP",
        eliteFavorite: "Favorito de Élite",
        label: "Sello",
        catNo: "Cat #",
        genre: "Género",
        country: "País",
        tracklist: "Lista de Temas",
        totalTracks: "PISTAS EN TOTAL",
        sonicSpectrum: "Espectro Sonoro",
        ownershipData: "Datos de Propiedad",
        collectors: "Coleccionistas",
        wanted: "Buscados"
    }
};
